version: '2'
services:
  postgres-game-library-dev-db:
    container_name: postgres-game-library-dev-db
    build: ./postgres/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=30b328e7919d38523f78c058604b9a19
  pgadmin-game-library-dev-db:
    container_name: pgadmin-game-library-dev-db
    build: ./pgadmin/
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: test@postgresql.org
      PGADMIN_DEFAULT_PASSWORD: postgres
    links:
      - postgres-game-library-dev-db
    logging:
      driver: "none"