version: '3.9'

services:

  postgres-game-library-dev-db:
    container_name: postgres-game-library-dev-db
    build: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USR}
      POSTGRES_PASSWORD: ${POSTGRES_PWD}

  pgadmin-game-library-dev-db:
    container_name: pgadmin-game-library-dev-db
    build: pgadmin
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PWD}
    links:
      - postgres-game-library-dev-db
    logging:
      driver: "none"